---

    - name: Remove unapropriate packages for CentOS
      yum:
        pkg:: "{{ bad_pkgs }}"
        state: absent

    - name: Install required packages and useful tools
      yum:
        pkg: "{{ required_centos_pkgs }}"
        state: installed
        update_cache: true

    - name: Add Docker CE repo list
      get_url:
        url: "{{ docker_centos_repolist_uri }}"
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0440
        validate_certs: no

    - name: Install Docker CE packages
      yum: pkg={{ item }} state=installed update_cache=true
      with_items:
        - "{{ dockerce_centos_pkgs }}"

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
