---

    - name: Remove inapropriate packages for CentOS
      yum:
        name: "{{ bad_pkgs }}"
        state: absent

    - name: Install required packages and useful tools
      yum:
        name: "{{ required_centos_pkgs }}"
        state: present
        update_cache: true

    - name: Add Docker CE repo list
      get_url:
        url: "{{ docker_centos_repolist_uri }}"
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0440
        validate_certs: no

    - name: Install Docker CE packages
      yum:
        name: "{{ dockerce_centos_pkgs }}"
        state: present
        update_cache: true

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
